# Gambas Action File 3.0

{ Actions
  { Action Draw_Lines
    Text = "Lines"
    Shortcut = ""
  }
  { Action Edit_Copy
    Text = "Copy"
    Shortcut = ""
  }
  { Action Edit_Cut
    Text = "Cut"
    Shortcut = ""
  }
  { Action Edit_Paste
    Text = "Paste"
    Shortcut = ""
  }
  { Action Edit_Redo
    Text = "Redo"
    Shortcut = ""
  }
  { Action Edit_Undo
    Text = "Undo"
    Shortcut = ""
  }
  { Action File_Open
    Text = "Open"
    Shortcut = ""
  }
  { Action File_Quit
    Text = "Quit"
    Shortcut = ""
  }
  { Action File_Save
    Text = "Save"
    Shortcut = ""
  }
  { Action File_SaveAs
    Text = "Save as"
    Shortcut = ""
  }
  { Action File_new
    Text = "New"
    Shortcut = ""
  }
  { Action File_previous
    Text = "Previous files"
    Shortcut = ""
  }
  { Action cadArc
    Text = "Arc"
    Shortcut = ""
  }
  { Action cadArray
    Text = "Array rectangular"
    Shortcut = ""
  }
  { Action cadAttdef
    Text = "Attdef"
    Shortcut = ""
  }
  { Action cadAttrib
    Text = "Attrib"
    Shortcut = ""
  }
  { Action cadCircle
    Text = "Circle"
    Shortcut = ""
  }
  { Action cadCopy
    Text = "Copy"
    Shortcut = ""
  }
  { Action cadEllipse
    Text = "Ellipse"
    Shortcut = ""
  }
  { Action cadLWPolyline
    Text = "Polyline"
    Shortcut = ""
  }
  { Action cadLeader
    Text = "Leader"
    Shortcut = ""
  }
  { Action cadLine
    Text = "Line"
    Shortcut = ""
  }
  { Action cadMText
    Text = "MText"
    Shortcut = ""
  }
  { Action cadMove
    Text = "Move"
    Shortcut = ""
  }
  { Action cadPan
    Text = "P"
    Picture = "$ToolButton"
  }
  { Action cadPoint
    Text = "Point"
    Shortcut = ""
  }
  { Action cadPolygon
    Text = "Polygon"
    Shortcut = ""
  }
  { Action cadRay
    Text = "Ray"
    Shortcut = ""
  }
  { Action cadRectangle
    Text = "Rectangle"
    Shortcut = ""
  }
  { Action cadSPline
    Text = "SPline"
    Shortcut = ""
  }
  { Action cadText
    Text = "Text"
    Shortcut = ""
  }
  { Action cadTrim
    Text = "Trim"
    Shortcut = ""
  }
  { Action cadZoomW
    Text = "W"
    Picture = "$ToolButton"
  }
  { Action cadZoome
    Text = "E"
    Picture = "$ToolButton"
  }
  { Action file_new
    Text = ""
    Picture = "icon:/32/new"
  }
  { Action file_open
    Text = ""
    Picture = "icon:/32/open"
  }
  { Action file_save
    Text = ""
    Picture = "icon:/32/save"
  }
  { Action file_saveas
    Text = ""
    Picture = "icon:/32/save-as"
  }
  { Action layers_delete
    Text = ""
    Picture = "$ToolButton"
  }
  { Action layers_form
    Text = ""
    Picture = "icon:/32/table"
  }
  { Action layers_new
    Text = "New"
    Picture = "$Button"
  }
}

