# Gambas Action File 3.0

{ Actions
  { Action File_Open
    Text = "Open"
    Shortcut = ""
  }
  { Action File_Quit
    Text = "Quit"
    Shortcut = ""
  }
  { Action File_Save
    Text = "Save"
    Shortcut = ""
  }
  { Action File_SaveAs
    Text = "Save as"
    Shortcut = ""
  }
  { Action File_previous
    Text = "Previous files"
    Shortcut = ""
  }
  { Action PDF_Export
    Text = ""
    Picture = "icon:/32/pdf"
  }
  { Action Print
    Text = ""
    Picture = "icon:/32/print"
  }
  { Action cadArea
    Text = ""
    Picture = "png/area.png"
  }
  { Action cadPan
    Text = ""
    Picture = "png/pan.png"
  }
  { Action cadProtractor
    Text = ""
    Picture = "png/protractor.png"
  }
  { Action cadRuler
    Text = ""
    Picture = "$ToolButton"
  }
  { Action cadZoomW
    Text = ""
    Picture = "png/zoomwindow.png"
  }
  { Action cadZoome
    Text = ""
    Picture = "png/zoomextents.png"
  }
  { Action exit
    Text = ""
    Picture = "icon:/32/cancel"
  }
  { Action file_open
    Text = ""
    Picture = "icon:/32/open"
  }
}

