# Gambas Action File 3.0

{ Actions
  { Action File_Open
    Text = "Open"
    Shortcut = ""
  }
  { Action File_Quit
    Text = "Quit"
    Shortcut = ""
  }
  { Action File_Save
    Text = "Save"
    Shortcut = ""
  }
  { Action File_SaveAs
    Text = "Save as"
    Shortcut = ""
  }
  { Action File_previous
    Text = "Previous files"
    Shortcut = ""
  }
  { Action about
    Text = "About this program"
    Picture = "$ToolButton"
  }
  { Action cadZoomW
    Text = "Zoom to a defined window"
    Picture = "$ToolButton"
  }
  { Action cadZoome
    Text = "Zoom to view all drawing"
    Picture = "$ToolButton"
  }
  { Action cadlayers
    Text = "Layer table"
    Picture = "$ToolButton"
  }
  { Action cofee
    Text = "Buy me a cofee!!!"
    Picture = "png/buymeacofee32.png"
  }
  { Action config
    Text = "Preferences"
    Picture = "$ToolButton"
  }
  { Action debugwindow
    Text = "Debugging window"
    Picture = "$ToolButton"
  }
  { Action dimstyle_change
    Text = ""
    Picture = "$ComboBox"
  }
  { Action dimstyles
    Text = "Dimension styles"
    Picture = "$ToolButton"
  }
  { Action file_new
    Text = "New"
    Picture = "$ToolButton"
  }
  { Action file_open
    Text = "Open"
    Picture = "$MenuButton"
  }
  { Action file_save
    Text = "Save"
    Picture = "$ToolButton"
  }
  { Action file_saveas
    Text = "Save as"
    Picture = "$ToolButton"
  }
  { Action print
    Text = ""
    Picture = "$ToolButton"
  }
  { Action redo
    Text = ""
    Picture = "$ToolButton"
  }
  { Action undo
    Text = ""
    Picture = "$ToolButton"
  }
}

